apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: s2i-pipeline
spec:
  params:
    - name: git-url
      description: Git repository URL
      default: git@github.com:OmdaMukhtar/simple-s2i.git
    - name: branch
      description: Git branch
      default: tekton
  tasks:
    - name: trigger-build
      taskSpec:
        steps:
          - name: start-s2i-build
            image: quay.io/openshift/origin-cli:4.12
            script: |
              #!/bin/sh
              set -e

              echo "Starting S2I build in namespace: $(context.pipelineRun.namespace)"

              oc start-build s2i-app \
                -n $(context.pipelineRun.namespace) \
                --wait
